Option to keep or drop some dice from those rolled
justinian/dice pull request #5
Opened 2017-02-28 22:45 UTC by olavmueller

2017-02-28 23:06 UTC, justinian commented
Oh, thanks for this PR! Great idea for this addition. Looks pretty much good to go, just a couple minor comments:

2017-02-28 23:10 UTC, justinian requested changes

2017-02-28 23:10 UTC, justinian commented on std.go
> +	fmt.Println( matches )
This looks like it might have been for testing? Let's pull this out.

2017-02-28 23:10 UTC, justinian commented on std.go
> +		Dropped:		 nil,
Looks like a tabs/spaces mismatch here - can you run the file through `gofmt`?

2017-02-28 23:10 UTC, justinian commented on std.go
> +	}
Not a huge deal, but you could make this a `switch` statement, which might look cleaner. I'm fine with it either way though, to be honest.

2017-03-01 18:53 UTC, olavmueller commented on std.go
> +	fmt.Println( matches )
Sure. Sorry.

2017-03-01 18:54 UTC, closed without merging