Add support for fudge dices.
justinian/dice pull request #8
Opened 2017-07-27 06:04 UTC by eduardostalinho

This PR adds support for [Fudge dice](https://en.wikipedia.org/wiki/Fudge_(role-playing_game_system)#Fudge_dice).

It can be rolled using `roll 4df`. Only subtract and add operations are supported.

2017-07-27 06:51 UTC, justinian commented
Awesome, Fudge dice! I've been playing some FATE lately, and somehow didn't think to add this.
Thanks for the PR. I've just got a couple comments, but otherwise it looks good.

2017-07-27 06:55 UTC, justinian requested changes

2017-07-27 06:55 UTC, justinian commented on fudge.go
> +		result.Rolls[i] = roll
Why not add the rolls to the total here, so you don't have to loop again down below?

2017-07-27 06:55 UTC, justinian commented on fudge_test.go
> +*/
Since these are just commented out, it's probably better to just delete them.

2017-07-27 06:55 UTC, justinian commented on fudge_test.go
> + * Std dice test cases
Update this from `Std` to `Fudge`

2017-07-27 16:01 UTC, eduardostalinho commented on fudge.go
> +		result.Rolls[i] = roll
You are right. This was just the first draft from StdDice.

I'm gonna change it.

2017-07-28 00:26 UTC, eduardostalinho commented
updated @justinian

2017-07-28 00:27 UTC, justinian approved these changes

2017-07-28 00:27 UTC, merged

2017-07-28 00:28 UTC, justinian commented
Awesome. Thanks a bunch, @eduardostalinho!